
# Generated by Django 6.0.7 on 2026-08-29 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image'),
        ('wishlist', '0002_wishlist_products_alter_wishlist_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # Add the new product field FIRST
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wishlisted_by',
                to='products.product',
            ),
        ),

        # Remove the old products field
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),

        # Add the unique constraint AFTER product exists
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),

        # Keep the user field configuration
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wishlist_items',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
