import os
import time
import requests

from django.core.management.base import BaseCommand
from django.conf import settings
from dotenv import load_dotenv

from products.models import Product


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()

PEXELS_API_KEY = os.getenv("PEXELS_API_KEY")

PEXELS_URL = "https://api.pexels.com/v1/search"


# ============================================================
# PRODUCT SEARCH KEYWORDS
#
# These help Pexels find more relevant photographs.
# ============================================================

CATEGORY_KEYWORDS = {

    "Mobiles": "smartphone mobile phone",
    "Laptops": "laptop computer",
    "Tablets": "tablet computer",
    "Headphones": "headphones",
    "Earphones": "earphones",
    "Earbuds": "wireless earbuds",
    "Smart Watches": "smart watch",
    "Smart Bands": "fitness smart band",
    "Mobile Accessories": "mobile phone accessories",
    "Laptop Accessories": "laptop accessories",
    "Computer Accessories": "computer accessories",
    "Keyboards": "computer keyboard",
    "Mice": "computer mouse",
    "Monitors": "computer monitor",
    "Speakers": "bluetooth speaker",
    "Televisions": "smart television",

    "T-Shirts": "t shirt clothing",
    "Shirts": "shirt clothing",
    "Jeans": "jeans clothing",
    "Sarees": "saree indian clothing",
    "Kurtis": "kurti indian clothing",
    "Lehengas": "lehenga indian clothing",

    "Shoes": "shoes footwear",
    "Running Shoes": "running shoes",
    "Sneakers": "sneakers",
    "Sandals": "sandals footwear",

    "Makeup": "makeup cosmetics",
    "Skincare": "skincare cosmetics",
    "Hair Care": "hair care products",
    "Perfumes": "perfume fragrance",

    "Furniture": "furniture",
    "Home Decor": "home decoration",
    "Bedsheets": "bedsheet bedroom",
    "Lighting": "home lighting lamp",

    "Cookware": "cookware kitchen",
    "Air Fryers": "air fryer",
    "Mixer Grinders": "mixer grinder kitchen",
    "Water Bottles": "water bottle",

    "Rice": "rice food",
    "Atta & Flour": "flour wheat food",
    "Spices": "indian spices",
    "Dry Fruits": "dry fruits almonds cashews",
    "Biscuits": "biscuits cookies food",

    "Cricket": "cricket equipment",
    "Football": "football equipment",
    "Badminton": "badminton equipment",
    "Yoga": "yoga equipment",
    "Fitness": "fitness equipment",

    "Toys": "children toys",
    "Educational Toys": "educational toys",
    "Board Games": "board games",
    "Puzzles": "jigsaw puzzle",

    "Books": "books",
    "Fiction Books": "fiction books",
    "Academic Books": "academic books",
    "Technology Books": "technology programming books",

    "Car Accessories": "car accessories",
    "Bike Accessories": "motorcycle accessories",
    "Helmets": "motorcycle helmet",

    "Luggage": "travel luggage",
    "Backpacks": "backpack",
    "Travel Accessories": "travel accessories",

    "Pet Supplies": "pet supplies",
    "Dog Supplies": "dog supplies",
    "Cat Supplies": "cat supplies",

    "Stationery": "stationery",
    "Pens": "pens",
    "Notebooks": "notebook",

    "Baby Products": "baby products",
    "Baby Clothing": "baby clothing",
    "Baby Care": "baby care products",
    "Diapers": "baby diapers",
    "Baby Accessories": "baby accessories",
}


# ============================================================
# GENERIC KEYWORD FALLBACK
# ============================================================

def get_search_query(product):

    product_name = product.name.strip()

    category_name = product.category.name.strip()

    category_keyword = CATEGORY_KEYWORDS.get(
        category_name,
        category_name
    )

    # Remove words that are automatically generated by
    # seed_products.py because they are not useful search terms.

    clean_product_name = product_name.replace(
        " Essential",
        ""
    ).replace(
        " Special",
        ""
    ).replace(
        "Premium ",
        ""
    )

    search_query = (
        f"{clean_product_name} "
        f"{category_keyword} "
        f"product"
    )

    return search_query


# ============================================================
# VALIDATE IMAGE
# ============================================================

def is_valid_image(content):

    if not content:
        return False

    if len(content) < 10000:
        return False

    # JPEG
    if content[:3] == b"\xff\xd8\xff":
        return True

    # PNG
    if content[:8] == b"\x89PNG\r\n\x1a\n":
        return True

    # WEBP
    if content[:4] == b"RIFF" and content[8:12] == b"WEBP":
        return True

    return False


# ============================================================
# COMMAND
# ============================================================

class Command(BaseCommand):

    help = (
        "Replace all existing product images with "
        "unique product-specific Pexels images"
    )

    def handle(self, *args, **kwargs):

        # ========================================================
        # CHECK API KEY
        # ========================================================

        if not PEXELS_API_KEY:

            self.stdout.write(
                self.style.ERROR(
                    "\nPEXELS_API_KEY not found in .env"
                )
            )

            self.stdout.write(
                "Add this to your .env file:"
            )

            self.stdout.write(
                "PEXELS_API_KEY=your_pexels_api_key"
            )

            return

        # ========================================================
        # PRODUCT DIRECTORY
        # ========================================================

        products_dir = os.path.join(
            settings.MEDIA_ROOT,
            "products"
        )

        os.makedirs(
            products_dir,
            exist_ok=True
        )

        # ========================================================
        # HEADERS
        # ========================================================

        headers = {
            "Authorization": PEXELS_API_KEY,
            "User-Agent": "DiyaMart Product Image Downloader"
        }

        # ========================================================
        # PRODUCTS
        # ========================================================

        products = Product.objects.select_related(
            "category"
        ).order_by(
            "id"
        )

        total = products.count()

        downloaded = 0
        failed = 0

        # Keep track of Pexels photo IDs already used.
        #
        # This prevents two products from receiving the
        # exact same Pexels photograph during this run.
        used_photo_ids = set()

        # ========================================================
        # HEADER
        # ========================================================

        self.stdout.write("")

        self.stdout.write(
            self.style.SUCCESS(
                "=========================================="
            )
        )

        self.stdout.write(
            self.style.SUCCESS(
                "     DIYAMART PRODUCT IMAGE FIXER"
            )
        )

        self.stdout.write(
            self.style.SUCCESS(
                "=========================================="
            )
        )

        self.stdout.write(
            f"Total products: {total}"
        )

        self.stdout.write("")

        self.stdout.write(
            self.style.WARNING(
                "IMPORTANT: Existing product images WILL be replaced."
            )
        )

        self.stdout.write("")

        # ========================================================
        # PROCESS PRODUCTS
        # ========================================================

        for index, product in enumerate(
            products,
            start=1
        ):

            self.stdout.write(
                f"[{index}/{total}] "
                f"Downloading: {product.name}"
            )

            search_query = get_search_query(
                product
            )

            # ----------------------------------------------------
            # We try several pages.
            #
            # This is important because requesting page=1 every
            # time can return the same first image.
            # ----------------------------------------------------

            success = False

            for page in range(1, 6):

                try:

                    # ------------------------------------------------
                    # SEARCH PEXELS
                    # ------------------------------------------------

                    params = {
                        "query": search_query,
                        "per_page": 20,
                        "page": page,
                        "orientation": "square",
                        "size": "medium",
                    }

                    response = requests.get(
                        PEXELS_URL,
                        headers=headers,
                        params=params,
                        timeout=30
                    )

                    # ------------------------------------------------
                    # RATE LIMIT
                    # ------------------------------------------------

                    if response.status_code == 429:

                        self.stdout.write(
                            self.style.WARNING(
                                "  Rate limit reached."
                            )
                        )

                        self.stdout.write(
                            "  Waiting 10 seconds..."
                        )

                        time.sleep(10)

                        response = requests.get(
                            PEXELS_URL,
                            headers=headers,
                            params=params,
                            timeout=30
                        )

                    # ------------------------------------------------
                    # API ERROR
                    # ------------------------------------------------

                    if response.status_code != 200:

                        self.stdout.write(
                            self.style.WARNING(
                                f"  Pexels API error: "
                                f"{response.status_code}"
                            )
                        )

                        continue

                    # ------------------------------------------------
                    # JSON
                    # ------------------------------------------------

                    data = response.json()

                    photos = data.get(
                        "photos",
                        []
                    )

                    if not photos:

                        continue

                    # ------------------------------------------------
                    # Find a photo that hasn't already been used.
                    # ------------------------------------------------

                    selected_photo = None

                    for photo in photos:

                        photo_id = photo.get(
                            "id"
                        )

                        if not photo_id:
                            continue

                        if photo_id in used_photo_ids:
                            continue

                        selected_photo = photo

                        break

                    # ------------------------------------------------
                    # If all photos on this page were already used,
                    # try the next page.
                    # ------------------------------------------------

                    if not selected_photo:

                        continue

                    photo_id = selected_photo.get(
                        "id"
                    )

                    image_sources = selected_photo.get(
                        "src",
                        {}
                    )

                    image_url = (
                        image_sources.get("large2x")
                        or
                        image_sources.get("large")
                        or
                        image_sources.get("medium")
                    )

                    if not image_url:

                        continue

                    # ------------------------------------------------
                    # DOWNLOAD IMAGE
                    # ------------------------------------------------

                    image_response = requests.get(
                        image_url,
                        timeout=30,
                        headers={
                            "User-Agent":
                            "DiyaMart Product Image Downloader"
                        }
                    )

                    if image_response.status_code != 200:

                        self.stdout.write(
                            self.style.WARNING(
                                "  Image download failed."
                            )
                        )

                        continue

                    image_content = (
                        image_response.content
                    )

                    # ------------------------------------------------
                    # VALIDATE
                    # ------------------------------------------------

                    if not is_valid_image(
                        image_content
                    ):

                        self.stdout.write(
                            self.style.WARNING(
                                "  Invalid image received."
                            )
                        )

                        continue

                    # ------------------------------------------------
                    # FILE NAME
                    # ------------------------------------------------

                    filename = (
                        f"product_{product.id}.jpg"
                    )

                    file_path = os.path.join(
                        products_dir,
                        filename
                    )

                    # ------------------------------------------------
                    # DELETE OLD FILE
                    # ------------------------------------------------

                    if product.image:

                        try:

                            old_path = (
                                product.image.path
                            )

                            if os.path.exists(
                                old_path
                            ):

                                os.remove(
                                    old_path
                                )

                        except (
                            ValueError,
                            AttributeError,
                            OSError
                        ):

                            pass

                    # ------------------------------------------------
                    # SAVE NEW IMAGE
                    # ------------------------------------------------

                    with open(
                        file_path,
                        "wb"
                    ) as image_file:

                        image_file.write(
                            image_content
                        )

                    # ------------------------------------------------
                    # UPDATE PRODUCT
                    # ------------------------------------------------

                    product.image = (
                        f"products/{filename}"
                    )

                    product.save(
                        update_fields=[
                            "image"
                        ]
                    )

                    # ------------------------------------------------
                    # MARK PHOTO AS USED
                    # ------------------------------------------------

                    used_photo_ids.add(
                        photo_id
                    )

                    downloaded += 1

                    success = True

                    self.stdout.write(
                        self.style.SUCCESS(
                            f"  ✓ Added unique image "
                            f"(Pexels ID: {photo_id})"
                        )
                    )

                    # ------------------------------------------------
                    # Show search query for debugging.
                    # ------------------------------------------------

                    self.stdout.write(
                        f"  Search: {search_query}"
                    )

                    break

                # ====================================================
                # REQUEST / GENERAL ERROR
                # ====================================================

                except requests.RequestException as e:

                    self.stdout.write(
                        self.style.WARNING(
                            f"  Network error: {e}"
                        )
                    )

                    time.sleep(2)

                except Exception as e:

                    self.stdout.write(
                        self.style.WARNING(
                            f"  Error: {e}"
                        )
                    )

            # ========================================================
            # FAILED PRODUCT
            # ========================================================

            if not success:

                failed += 1

                self.stdout.write(
                    self.style.ERROR(
                        f"  ✗ Could not find image for: "
                        f"{product.name}"
                    )
                )

            # ========================================================
            # DELAY
            # ========================================================

            time.sleep(0.4)

        # ============================================================
        # FINAL REPORT
        # ============================================================

        self.stdout.write("")

        self.stdout.write(
            self.style.SUCCESS(
                "=========================================="
            )
        )

        self.stdout.write(
            self.style.SUCCESS(
                "       IMAGE DOWNLOAD COMPLETE"
            )
        )

        self.stdout.write(
            self.style.SUCCESS(
                "=========================================="
            )
        )

        self.stdout.write(
            f"Total products : {total}"
        )

        self.stdout.write(
            self.style.SUCCESS(
                f"Images replaced: {downloaded}"
            )
        )

        self.stdout.write(
            self.style.ERROR(
                f"Failed         : {failed}"
            )
        )

        self.stdout.write(
            self.style.SUCCESS(
                "=========================================="
            )
        )

        self.stdout.write("")

        self.stdout.write(
            "Images stored in:"
        )

        self.stdout.write(
            os.path.join(
                settings.MEDIA_ROOT,
                "products"
            )
        )

        self.stdout.write("")

        self.stdout.write(
            self.style.WARNING(
                "If some products failed, run this command"
                " again after checking your Pexels API limit."
            )
        )
